# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_neighbour', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_neighbour.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
