# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-04 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch_neighbour', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_photo', models.ImageField(upload_to='business/')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department_description', models.TextField(blank=True, max_length=200, null=True)),
                ('department_email', models.CharField(blank=True, max_length=100, null=True)),
                ('department_phone', models.IntegerField(blank=True, null=True)),
                ('department_box', models.CharField(blank=True, max_length=100, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_neighbour.Neighbourhood')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='watch_neighbour.Profile'),
        ),
    ]
