# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_neighbour', '0005_auto_20180804_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_neighbour.Neighbourhood'),
        ),
    ]
