# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_neighbour', '0006_post_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_for', to='watch_neighbour.Neighbourhood'),
        ),
    ]
