# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_neighbour', '0007_auto_20180806_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='posts_for', to='watch_neighbour.Neighbourhood'),
            preserve_default=False,
        ),
    ]
