# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_neighbour', '0009_auto_20180806_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_neighbour.Neighbourhood'),
        ),
    ]
